env:
  - PLATFORM=debian-jessie
  - PLATFORM=debian-jessie-upstream

sudo: required

language: python

services:
  - docker

script:
  - docker build -f tests/$PLATFORM.Dockerfile -t test-$PLATFORM . && docker run --name $PLATFORM test-$PLATFORM

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
