---

- name: APT | Install setuptools
  apt:
    pkg: python-setuptools
    update_cache: yes
    cache_valid_time: 3600

- name: PIP | Install docker-python
  pip:
    name: docker-py

- name: INCLUDE | Upstream install
  include: upstream.yml
