---

- name: APT | Install setuptools
  apt:
    pkg: python-setuptools
    update_cache: yes
    cache_valid_time: 3600

- name: PIP | Install docker-python
  pip:
    name: docker

- name: APT | Install deps
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - apt-transport-https
    - ca-certificates
    - gnupg2
    - software-properties-common

- name: APT_KEY | Get APT key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

- name: APT_REPOSITORY | Add Docker repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"

- name: APT | Install docker
  apt:
    pkg: "docker-ce{% if docker_version is not none %}={{ docker_version }}{% endif %}"
