---
- name: APT | Install deps
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - apt-transport-https
    - ca-certificates
    - cgroupfs-mount

- name: APT_KEY | Get APT key
  apt_key: >
    keyserver=hkp://p80.pool.sks-keyservers.net:80
    id=58118E89F3A912897C070ADBF76221572C52609D

- name: APT_REPOSITORY | Add Docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo {{ ansible_distribution | lower }}-{{ ansible_distribution_release }} main'

- name: APT | Install docker
  apt: pkg=docker-engine
